apps/synthmark.cpp, source/tools/LatencyMarkHarness.h
When the maximum number of voces is specified, it is possible to define
the way the voices are chosen, that can be:
- random: randomly chosen in the range [-n, -N];
- linear loop: increases starting from -n with rate "NOTES_PER_STEP / 2"
and, when it reaches -N, starts back from -n;
- switch: periodically switches between -n and -N.
=> Different voices configurations for LatencyMark

source/tools/UtilizationMarkHarness.h
=> utilization: fix printf

android/app/src/main/java/com/sonodroid/synthmark/MainActivity.java, android/app/src/main/res/layout/activity_main.xml, source/tools/NativeTest.h
Add button that shares the resulting report to GMail, Drive, etc.
=> share: set burst to 96, add Share Result

source/tools/AutomatedTestSuite.h
=> automated: fix BIG.little labels

android/app/src/main/cpp/OpenSLHostThread.cpp, android/app/src/main/cpp/OpenSLHostThread.h, source/tools/AudioSinkBase.h, source/tools/AutomatedTestSuite.h, source/tools/BinCounter.h, source/tools/IAudioSinkCallback.h, source/tools/JitterMarkHarness.h, source/tools/LatencyMarkHarness.h, source/tools/TestHarnessBase.h, source/tools/TimingAnalyzer.h
Preparation for adding the clock ramp test.
=> Refactoring but nothing substantial.

android/app/src/main/cpp/OpenSLAudioSink.cpp, android/app/src/main/cpp/OpenSLAudioSink.h, apps/synthmark.cpp, source/SynthMark.h, source/tools/AudioSinkBase.h, source/tools/ChangingVoiceHarness.h, source/tools/ClockRampHarness.h, source/tools/JitterMarkHarness.h, source/tools/TestHarnessBase.h, source/tools/TimingAnalyzer.h, source/tools/VirtualAudioSink.h, source/tools/dummy.cpp
Measure how long it takes for the CPU clock frequency to respond
to an increase in workload.
=> Add ClockRamp test using -tc

apps/synthmark.cpp
=> Check for invalid numeric arguments on command line.

apps/synthmark.cpp, source/tools/CustomHostCpuManager.h, source/tools/HostTools.cpp, source/tools/HostTools.h, source/tools/NativeTest.h, source/tools/VirtualAudioSink.h
=> add -w option to enable SCHED_DEADLINE experiment

android/app/src/main/java/com/sonodroid/synthmark/AppObject.java
Also list the exclusive core IDs.
Fixes #38
=> synthmark app: show schedtune.boost

android_mk/jni/Android.mk, source/tools/SynthMarkCommand.cpp, source/tools/SynthMarkCommand.h
This will make it easier to edit in Android Studio.
No functionality was changed.
Fixes #65
=> synthmark: move guts of main() to tools folder

source/tools/NativeTest.h, source/tools/SynthMarkCommand.cpp
=> app: add AutomatedSuite to app tests

scripts/android/autopower/README.md, scripts/android/autopower/autopower.py, scripts/android/autopower/test_once.sh
As well as removing deprecated modules. Adding additional usage documentation to
README.md.
=> Updating autopower.py script to take more accurate measurements.

android/app/build.gradle, android/app/src/main/AndroidManifest.xml, android/app/src/main/java/com/sonodroid/synthmark/AppObject.java, android/app/src/main/java/com/sonodroid/synthmark/BaseActivity.java, android/app/src/main/java/com/sonodroid/synthmark/MainActivity.java, android/app/src/main/java/com/sonodroid/synthmark/Param.java, android/app/src/main/java/com/sonodroid/synthmark/SettingsActivity.java, android/build.gradle, android/gradle/wrapper/gradle-wrapper.properties, source/tools/NativeTest.h, source/tools/SynthMarkResult.h
This will allow us to run automated tests of SynthMark without root access.
Sample command:
adb shell am start -n com.sonodroid.synthmark/.MainActivity --es test jitter \
--ei core_affinity 1  --es file /sdcard/test20190611.txt
Fixes #80
=> app: run test from an Intent

scripts/android/autopower/README.md, scripts/android/autopower/monsoon.py
This script controls the Monsoon Power meter.
Note that there are many versions of this script that are slightly different.
Also there are some "monsoon.py" that are completely different.
So we wanted to get this copy under version control.
=> autopower: add monsoon.py script

source/tools/HostTools.h, source/tools/VirtualAudioSink.h
=> allow failure of sched_setaffinity()

android/app/src/main/java/com/sonodroid/synthmark/AppObject.java, android/app/src/main/java/com/sonodroid/synthmark/BaseActivity.java
=> Remove some log spam.

android/app/build.gradle, android/app/src/main/java/com/sonodroid/synthmark/AppObject.java, android/app/src/main/java/com/sonodroid/synthmark/MainActivity.java
Crashes on some devices!
Log result on main screen.
Bump version to 1.8
=> app: catch exception getExclusiveCores()

source/SynthMark.h, source/tools/SynthMarkCommand.cpp, source/tools/TestHarnessParameters.h, source/tools/UtilClampAudioBehavior.h, source/tools/UtilClampController.h, source/tools/VirtualAudioSink.h, source/tools/scheddl.h
Initial class to manage UtilClamp values
Signed-off-by: Biagio Ferri <biagio.ferri@yahoo.com>
=> Add UtilClamp Controller

source/tools/VirtualAudioSink.h
Put all in the RT audio thread.
=> Consolidate all UtilClamp control

source/tools/SynthMarkCommand.cpp, source/tools/VirtualAudioSink.h
For the command line executable only.
=> Add -u option for UtilClamp

source/SynthMark.h, source/tools/AudioSinkBase.h, source/tools/SynthMarkCommand.cpp, source/tools/TestHarnessParameters.h
Display scheduler better, mask off high RESET bit.
Error if -N specified but not used.
=> bump to 1.23

android/app/build.gradle, source/tools/AudioSinkBase.h, source/tools/LatencyMarkHarness.h, source/tools/NativeTest.h, source/tools/RealAudioSink.h
Was ignoring initial setting.
Also bump to V1.10
=> Fix setting buffer size for real audio mode.

android/app/CMakeLists.txt, android_mk/jni/Android.mk, source/SynthMark.h, source/tools/AdpfWrapper.cpp, source/tools/AdpfWrapper.h, source/tools/AudioSinkBase.h, source/tools/HostTools.h, source/tools/NativeTest.h, source/tools/RealAudioSink.h, source/tools/SynthMarkCommand.cpp, source/tools/VirtualAudioSink.h
Enables boosting of CPU performance.
Version 1.25
=> add ADPF support through dlsym()

android/app/build.gradle, source/tools/NativeTest.h
Make it easier to select a specific number of voices.
This makes it easier to repeat experiments.
Also bump version to 1.11
=> app: quantize num voices in slider

linux/Makefile, source/tools/CpuAnalyzer.h, source/tools/HostTools.h, source/tools/SynthMarkCommand.cpp
Use C++14
Prevent use of AAudio on Linux.
Handle more CPUs so it can run on a CloudTop.
=> Fix Linux build

android/app/build.gradle, android/app/src/main/AndroidManifest.xml, android/app/src/main/cpp/native-lib.cpp, android/app/src/main/cpp/native-lib.h, android/app/src/main/java/com/mobileer/synthmark/AppObject.java, android/app/src/main/java/com/mobileer/synthmark/BaseActivity.java, android/app/src/main/java/com/mobileer/synthmark/FakeKeyGenerator.java, android/app/src/main/java/com/mobileer/synthmark/MainActivity.java, android/app/src/main/java/com/mobileer/synthmark/Param.java, android/app/src/main/java/com/mobileer/synthmark/SettingsActivity.java, android/app/src/main/res/layout/activity_main.xml, android/app/src/main/res/layout/activity_settings.xml
because sonodroid.com is no longer owned by Google.
Fixes #135
=> Move package from sonodroid to mobileer

android/app/build.gradle, android/app/src/main/AndroidManifest.xml, android/build.gradle, android/gradle.properties, android/gradle/wrapper/gradle-wrapper.properties
=> Upgrade gradle and SDK

android/app/build.gradle
Leave the "debuggable true" so the bug can be reproduced.
=> Remove signingConfig from gradle file
