google/synthmark

- source/tools/TestHarnessBase.h
Some CSV parsers get in trouble with the last comma in the header of
the CSV histogram, so it is removed.
> TestHarnessBase: remove last comma in CSV header

- .travis.yml
- linux/Makefile
- source/tools/HostTools.h
- source/tools/TestHarnessBase.h
Fixed few missing things to use SynthMark on Linux targets.
Now it can be successfully compiled by using:
`$ make -f linux/Makefile`
To simplify the software development interaction, I also added a Travis-CI configuration file.
> Linux environment

- source/SynthMark.h
- source/synth/Synthesizer.h
- source/tools/LatencyMarkHarness.h
- source/tools/TestHarnessBase.h
- source/tools/VoiceMarkHarness.h
It now always starts with the -n voice count and transitions
to the -N voice count after a few seconds. Then it repeats.
The pattern starts over with the -n count whenever a glitch is detected.
This help us consistently detect problems related to the response time
of the CPU governor.
> LatencyMark: fix voice count behavior

- android/app/CMakeLists.txt
- android/app/build.gradle
- android/app/src/main/cpp/OpenSLHostThread.h
- android_mk/jni/Android.mk
- android_mk/jni/Application.mk
- apps/synthmark.cpp
- source/SynthMark.h
- source/aaudio/AAudioHostThread.cpp
- source/aaudio/AAudioHostThread.h
- source/tools/AudioSinkBase.h
- source/tools/AutomatedTestSuite.h
- source/tools/HostThreadFactory.h
- source/tools/HostTools.h
- source/tools/NativeTest.h
- source/tools/TestHarnessBase.h
- source/tools/VirtualAudioSink.h
So we can get BOOST mode for better performance.
This will match the thread type used by AAudio
and OpenSL ES.
> aaudio: use AAudio thread for callback

- apps/synthmark.cpp
- source/tools/AutomatedTestSuite.h
- source/tools/JitterMarkHarness.h
- source/tools/LatencyMarkHarness.h
- source/tools/NativeTest.h
- source/tools/TestHarnessBase.h
- source/tools/TestHarnessParameters.h
- source/tools/TimingAnalyzer.h
- source/tools/UtilizationMarkHarness.h
- source/tools/UtilizationSeriesHarness.h
- source/tools/VirtualAudioSink.h
- source/tools/VoiceMarkHarness.h
The -ts option allow the user to request a series of utilization
benchmarks with increasing numbers of voices.
The results are printed in CSV format so that they can be easily
plotted.
The -N option can be used to set the upper limit. If not specified
then a VoiceMark95 will be run to determine the upper limit.
Test: adb shell synthmark -ts
> synthmark: add series of utilization tests

- android/app/src/main/res/values/strings.xml
- source/tools/LatencyMarkHarness.h
- source/tools/NativeTest.h
- source/tools/TestHarnessParameters.h
- source/tools/VoiceMarkHarness.h
Extract common base class TestVoiceMark and other tests.
This makes it easier to add new tests.
> Add UtilizationMark and ClockRamp to Android app

- apps/synthmark.cpp
This was not tested on 8.1. But it does make some needed improvements.
> Fix command line argument validity check.

- source/tools/UtilizationMarkHarness.h
- source/tools/VoiceMarkHarness.h
Also cleanup format.
And put '=' after "Underruns".
> Show normalized voices for UtilizationMark

- apps/synthmark.cpp
- source/tools/CustomHostCpuManager.h
- source/tools/HostTools.h
- source/tools/LatencyMarkHarness.h
- source/tools/VirtualAudioSink.h
- source/tools/scheddl.h
Add the custom SCHED_DEADLINE scheduler with adaptive bandwidth allocation, based on the number of voices.
> Custom CPU manager uses SCHED_DEADLINE

- apps/synthmark.cpp
- source/tools/AudioSinkBase.h
- source/tools/ClockRampHarness.h
- source/tools/CpuAnalyzer.h
- source/tools/JitterMarkHarness.h
- source/tools/LatencyMarkHarness.h
- source/tools/TimingAnalyzer.h
- source/tools/UtilizationMarkHarness.h
- source/tools/VirtualAudioSink.h
Misc cleanup.
Set initial bursts per buffer for all tests.
Fix underrun count, which was overcounting.
Add average.wakeup.delay.micros as part of histogram.
Change various value names to use dotted format,
for example "Underruns " to underrun.count = ".
> Cleanup and print average wakeup delay

- source/tools/CustomHostCpuManager.h
- source/tools/VirtualAudioSink.h
The previous maximum bandwidth assigned to the DL task was starving some
Android services, causing the system to be unstable.
> CustomHostCpuManager: DL starves RT

- android/app/src/main/res/layout/activity_main.xml
- android/app/src/main/res/values/strings.xml
- source/synth/PitchToFrequency.h
- source/synth/Synthesizer.h
- source/tools/AudioSinkBase.h
- source/tools/ChangingVoiceHarness.h
- source/tools/HostTools.h
- source/tools/ITestHarness.h
- source/tools/LatencyMarkHarness.h
- source/tools/LogTool.h
- source/tools/NativeTest.h
- source/tools/SynthMarkCommand.cpp
- source/tools/TestHarnessParameters.h
- source/tools/VirtualAudioSink.h
Change some printfs to log()
Break result into lines to avoid buffer limit.
Make app and command line more similar.
Fixes #68
> app: cleanup logs

- android/app/build.gradle
- source/SynthMark.h
- source/aaudio/AAudioHostThread.cpp
- source/aaudio/AAudioHostThread.h
About a third of the time. SynthMark would hang when the test was finished.
It would then never print the test results.
This was caused by returning AAUDIO_CALLBACK_RESULT_STOP from the callback
and then immediately closing the stream. This caused a race condition.
The fix involves returning AAUDIO_CALLBACK_RESULT_CONTINUE and then preventing
the callbacks from executing the thread procedure multiple times.
Fixes #78
> synthmark: fix hang at end of test

- source/tools/LatencyMarkHarness.h
With reference to issue #82 , this basic patch should solve it.
resetBinarySearch() in searchForLowestLatency() was resetting the search
method previously defined in searchForLowestLatency()'s caller.
Just remove this resetBinarySearch() call.
> LatencyMark: searchForLowestLatency keeps search method

- source/tools/NativeTest.h
- source/tools/VirtualAudioSink.h
Fill the slider labels dynamically.
Fixes #98
> Limit Core Affinity to number of actual CPUs

- android/app/CMakeLists.txt
- android/app/src/main/cpp/native-lib.cpp
- android_mk/jni/Android.mk
- source/SynthMark.h
- source/tools/AudioSinkBase.h
- source/tools/HostTools.h
- source/tools/IAudioSinkCallback.h
- source/tools/LatencyMarkHarness.h
- source/tools/NativeTest.h
- source/tools/RealAudioSink.h
- source/tools/SynthMarkCommand.cpp
- source/tools/VirtualAudioSink.h
This allows us to test the effect of ADPF in AAudio.
Enable using -a2 option.
You will hear the output of the synthesized notes.
Note that more notes will sound quieter than few notes because
we divide the output by the number of notes to avoid clipping.
> Add real-time audio output.

- source/tools/AudioSinkBase.h
- source/tools/NativeTest.h
- source/tools/SynthMarkCommand.cpp
This allows SynthMark to measure the effect of ADPF when integrated into AAudio.
Also add a new test_start_delay so that we can let the touch boost
die down before running our benchmarks.
> synthmark: add audio_level to app

- source/tools/AudioSinkBase.h
- source/tools/SynthMarkCommand.cpp
- source/tools/VirtualAudioSink.h
Use -uM where M is >2.
Will set sched_util_min = M
Test: synthmark -tj -n1 -N75 -a1 -u0
Test: synthmark -tj -n1 -N75 -a1 -u2
Test: synthmark -tj -n1 -N75 -a1 -u165
> Support fixed uclamp_min value.

- linux/Makefile
Before this change, running CC=/path/to/c-compiler CXX=/path/to/c++-compiler make -f linux/Makefile would use the C compiler instead of the C++ one. Furthermore, GNU make sets automatically CC and CXX if they were not explicitly set.
> Name C++ compiler env var properly

- source/tools/Params.h
Compiler was warning about getName() going out of scope so I stashed it in a variable.
> Fix scope of named parameter

- source/tools/LatencyMarkHarness.h
Fixes #142
getFramesPerBurst() was zero
> Fix buffer.size.frames in LatencyMark
